version: '3.8'

services:
  expo:
    build: .
    ports:
      - "8081:8081"     # Metro bundler
      - "19000:19000"   # Expo dev server
      - "19001:19001"   # Debugging
      - "19002:19002"   # Expo web UI
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
